### ISSUE TITLE
`forge setup` doesn't work with `Gitlab` private container registry

### ISSUE THREAD

**Issue by makeittotop** [datawire/forge#39] opened 2017-08-30 04:12 UTC
First up, kudos to the entire team as `forge` is awesome !

Let's say the container registry is this :- **gitlab.example.com:4567/username/userproject**

In this case, the forget setup would fail even after the image push/pull has succeeded because the validation in `docker.py:registry_get` gets a 404 as it's looking at an incorrect URL 

The URL that gets constructed in `docker.py:registry_get` is `gitlab.example.com:4567/username/userproject/v2/username/forge_test/manifests/dummy` which is incorrect and the API returns a 404 which doesn't get handled correctly. 

It should rather be `gitlab.example.com:4567/v2/username/userproject/username/forge_test/manifests/dummy`

**Comment by makeittotop** [comment] 2017-08-30 04:23
Error log :-

validate: 1 child task(s) errored
  validate: 1 child task(s) errored
    pull: gitlab.example.com:4567/makeittotop/k8s-flask-app/forge-setu...
    tag: gitlab.example.com:4567/makeittotop/k8s-flask-app/forge-setu... forge_test dummy
    push: forge_test dummy -> gitlab.example.com:4567/makeittotop/k8s-flask-app/makeittotop/forge_test:dummy
    remote_exists: forge_test dummy -> unexpected error
   
      Traceback (most recent call last):
        File "/usr/home/makeittotop/.pex/install/Forge-0.2.15-py2-none-any.whl.b7d4ea7bf71cec0bb12a5a80eb168bad7c2e062b/Forge-0.2.15-py2-none-any.whl/forge/cli.py", line
 139, in validate
          dr.validate()
        File "/usr/home/makeittotop/.pex/install/Forge-0.2.15-py2-none-any.whl.b7d4ea7bf71cec0bb12a5a80eb168bad7c2e062b/Forge-0.2.15-py2-none-any.whl/forge/docker.py", l
ine 117, in validate
          assert self.remote_exists(name, version)
        File "/usr/home/makeittotop/.pex/install/Forge-0.2.15-py2-none-any.whl.b7d4ea7bf71cec0bb12a5a80eb168bad7c2e062b/Forge-0.2.15-py2-none-any.whl/forge/docker.py", l
ine 66, in remote_exists
          result = response.json()
        File "/usr/home/makeittotop/.pex/install/requests-2.14.2-py2.py3-none-any.whl.2cba8798c4d13b9f10391b16f854a07c0b2e065d/requests-2.14.2-py2.py3-none-any.whl/reque
sts/models.py", line 885, in json
          return complexjson.loads(self.text, **kwargs)
        File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
          raise ValueError(errmsg("Extra data", s, end, len(s)))
      ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)

**Comment by plombardi89** [comment] 2017-08-30 20:01
I suspect this might be an issue for Amazon ECR as well. I've been meaning to test this so i suppose I will go do that right now.

**Comment by plombardi89** [comment] 2017-08-30 20:48
So for ECR we need to update `forge/docker.py`

Old Code: `if result['errors'][0]['code'] == 'MANIFEST_UNKNOWN:`

New Code: `if result['errors'][0]['code'] in ('MANIFEST_UNKNOWN', 'NAME_UNKNOWN'):`

**Comment by rhs** [comment] 2017-08-31 10:40
@makeittotop Can you supply exactly the values you are supplying to forge setup? I'd like to try to reproduce this locally.

Thanks

**Comment by rhs** [comment] 2018-03-01 21:48
FYI, the current verison of forge seems to work fine with gitlab, and since I just recently added an integration test as part of the main forge test suite, I'm going to close this issue. Please feel free to file a new issue if you still are running into problem.s

**Closed by rhs** 2018-03-01 21:48 UTC
Labels: Bug
