### ISSUE TITLE
Setup return error

### ISSUE THREAD

**Issue by Bkamau** [datawire/forge#125] opened 2018-01-05 07:20 UTC
After installing, setup return error . 
Login Succeeded
║ docker pull registry.hub.docker.com/datawire/forge-setup-test:1
║ 1: Pulling from datawire/forge-setup-test
║ Digest: sha256:c0537ff6a5218ef531ece93d4984efc99bbf3f7497c0a7726c88e2bb7584dc96
║ Status: Image is up to date for registry.hub.docker.com/datawire/forge-setup-test:1
║ docker tag registry.hub.docker.com/datawire/forge-setup-test:1 registry.hub.docker.com/forge_test:dummy
║ docker push registry.hub.docker.com/forge_test:dummy
║ The push refers to a repository [registry.hub.docker.com/forge_test]
║ e154057080f4: Preparing
║ error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!doctype html>\n<html class=\"no-js\" lang=\"\">\n    <head>\n        <meta charset=\"utf-8\">\n        <meta http-.........

Same error output

 11 tasks run, 1 errors
║   setup: command 'docker push registry.hub.docker.com/forge_test:dummy' failed[1]: The push refers to a repository [registry.hub.docker.com/forge_test]
║ e154057080f4: Preparing
║ error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!doctype html>\n<html class=\"no-js\" lang=\"\">\n

**Comment by richarddli** [comment] 2018-01-05 16:14
Thanks for the bug report! Do you mind attaching the full `forge.log` file? It should be in your `/tmp` directory.

**Comment by plombardi89** [comment] 2018-01-08 13:29
I tried to reproduce the issue and I was able to reproduce it when using the `generic` repository type (btw this is horribly named) and then entering `-` for the organization / repository. 

The problem is that that this isn't valid for Docker Hub `registry.hub.docker.com/forge_test:dummy` it should be something like `registry.hub.docker.com/${NAMESPACE}/forge_test:dummy` but because we used `-` during `forge setup` it fails.

**Comment by rhs** [comment] 2018-01-22 20:34
This should be fixed in forge 0.3.25.

**Closed by rhs** 2018-01-22 20:34 UTC
Labels: Bug
